import {
  buildLearnerExportContent,
  buildRestorePreview,
  computeExportIntegrity,
  defaultPrivacyWarnings,
  makeExportFilePath,
  makeLearnerExportManifest,
  requireRestoreConfirmation,
  validateLearnerExportManifest,
  type LearnerExportManifest,
  type RestoreConfirmation,
  type RestorePreview,
  type SavedOccurrence,
  type SavedOccurrenceSourceContext,
  type UUID,
} from '@lingotorte/domain';
import type { LocalStore, LocalStoreSnapshot } from './localStore';

export type ExportLearnerStateResult = Readonly<{
  manifest: LearnerExportManifest;
  filePath: string;
}>;

export class ExportService {
  constructor(
    private readonly store: LocalStore,
    private readonly applicationVersion: string,
    private readonly deviceId?: string,
  ) {}

  buildManifest(): LearnerExportManifest {
    const snapshot = this.store.snapshot();
    const withTranscriptTrackContext = <T extends { sourceContext: SavedOccurrenceSourceContext }>(record: T): T => {
      const track = snapshot.subtitleTracks[record.sourceContext.subtitleTrackId];
      if (!track) return record;
      const transcriptTrack: NonNullable<SavedOccurrenceSourceContext['transcriptTrack']> = {
        trackId: track.id,
        status: track.transcriptStatus,
        sourceKind: track.transcriptSourceKind,
        trackVersion: track.trackVersion,
        ...(track.provenance.sourceUrl !== undefined ? { sourceUrl: track.provenance.sourceUrl } : {}),
        ...(track.provenance.sourceVideoId !== undefined ? { sourceVideoId: track.provenance.sourceVideoId } : {}),
        ...(track.provenance.retrievedAt !== undefined ? { retrievedAt: track.provenance.retrievedAt } : {}),
        ...(track.provenance.generatedAt !== undefined ? { generatedAt: track.provenance.generatedAt } : {}),
        ...(track.provenance.isAutoGenerated !== undefined ? { isAutoGenerated: track.provenance.isAutoGenerated } : {}),
        ...(track.provenance.engine !== undefined ? { engine: track.provenance.engine } : {}),
        ...(track.provenance.modelName !== undefined ? { modelName: track.provenance.modelName } : {}),
        ...(track.provenance.modelVersion !== undefined ? { modelVersion: track.provenance.modelVersion } : {}),
        ...(track.provenance.parentTrackId !== undefined ? { parentTrackId: track.provenance.parentTrackId } : {}),
        ...(track.provenance.parentTrackSha256 !== undefined ? { parentTrackSha256: track.provenance.parentTrackSha256 } : {}),
        warningFlags: Array.from(new Set([...(track.provenance.warningFlags ?? []), ...(track.qualityReport?.warningFlags ?? [])])),
        ...(track.qualityReport?.approvedAt !== undefined ? { approvedAt: track.qualityReport.approvedAt } : {}),
      };
      return { ...record, sourceContext: { ...record.sourceContext, transcriptTrack } };
    };
    const content = buildLearnerExportContent({
      savedItems: Object.values(snapshot.savedItems),
      savedOccurrences: Object.values(snapshot.savedOccurrences).map((occurrence: SavedOccurrence) => withTranscriptTrackContext(occurrence)),
      reviewCards: Object.values(snapshot.reviewCards),
      reviewCardStates: Object.values(snapshot.reviewCardStates),
      reviewEvents: [...snapshot.reviewEvents],
      practiceAttempts: snapshot.practiceAttempts.map((attempt) => withTranscriptTrackContext(attempt)),
    });
    const integrity = computeExportIntegrity(content);
    const manifestInput: Parameters<typeof makeLearnerExportManifest>[0] = {
      applicationVersion: this.applicationVersion,
      privacyWarnings: defaultPrivacyWarnings(true),
      content,
      integrity,
    };
    if (this.deviceId !== undefined) {
      (manifestInput as unknown as Record<string, string>).deviceId = this.deviceId;
    }
    return makeLearnerExportManifest(manifestInput);
  }

  exportToFile(directory: string): ExportLearnerStateResult {
    const manifest = this.buildManifest();
    const filePath = makeExportFilePath(directory, manifest.exportedAt);
    return { manifest, filePath };
  }
}

export class RestoreService {
  constructor(private readonly store: LocalStore) {}

  preview(manifest: LearnerExportManifest): RestorePreview {
    const snapshot = this.store.snapshot();
    return buildRestorePreview(manifest, {
      savedItems: snapshot.savedItems,
      savedOccurrences: snapshot.savedOccurrences,
      reviewCards: snapshot.reviewCards,
      reviewCardStates: snapshot.reviewCardStates,
      reviewEvents: snapshot.reviewEvents,
      practiceAttempts: snapshot.practiceAttempts,
    });
  }

  restore(manifest: LearnerExportManifest, confirmation: RestoreConfirmation): LocalStoreSnapshot {
    if (!confirmation.confirmOverwrite) {
      throw new TypeError('Restore refused: merge/update confirmation not supplied');
    }
    const preview = this.preview(manifest);
    if (preview.overwriteConfirmationRequired && !confirmation.confirmOverwrite) {
      throw new TypeError('Restore refused: local data exists and merge/update was not confirmed');
    }
    const acknowledged = new Set(confirmation.acknowledgedWarnings);
    for (const warning of preview.warnings) {
      if (!acknowledged.has(warning.kind)) {
        throw new TypeError(`Restore refused: warning ${warning.kind} not acknowledged`);
      }
    }

    for (const item of manifest.content.savedItems) {
      this.store.putSavedItem(item);
    }
    for (const occurrence of manifest.content.savedOccurrences) {
      this.store.putSavedOccurrence(occurrence);
    }
    for (const card of manifest.content.reviewCards) {
      this.store.putReviewCard(card);
    }
    for (const state of manifest.content.reviewCardStates) {
      this.store.putReviewCardState(state);
    }
    for (const event of manifest.content.reviewEvents) {
      this.store.addReviewEvent(event);
    }
    for (const attempt of manifest.content.practiceAttempts) {
      this.store.addPracticeAttempt(attempt);
    }

    return this.store.snapshot();
  }

  static validateManifest(value: unknown): LearnerExportManifest {
    return validateLearnerExportManifest(value);
  }

  static requireConfirmation(value: unknown): RestoreConfirmation {
    return requireRestoreConfirmation(value);
  }
}

export function extractDeviceId(deviceId: UUID | undefined): UUID | undefined {
  return deviceId;
}
