import { asRecord, requireNonNegativeInteger, requireSha256, requireString } from './guards';
import type { SavedOccurrenceSourceContext, TranscriptTrackSourceContext, TranscriptWarningFlag } from './types';

function validateRange(value: unknown, label: string, startKey: string, endKey: string): Readonly<{ start: number; end: number }> {
  const record = asRecord(value, label);
  const start = requireNonNegativeInteger(record, startKey);
  const end = requireNonNegativeInteger(record, endKey);
  if (end <= start) {
    throw new TypeError(`${label}.${endKey} must be greater than ${label}.${startKey}`);
  }
  return { start, end };
}

function validateTokenSpan(value: unknown): SavedOccurrenceSourceContext['tokenSpan'] {
  const record = asRecord(value, 'tokenSpan');
  const startToken = requireNonNegativeInteger(record, 'startToken');
  const endToken = requireNonNegativeInteger(record, 'endToken');
  if (endToken <= startToken) {
    throw new TypeError('tokenSpan.endToken must be greater than tokenSpan.startToken');
  }
  return { startToken, endToken };
}

export function validateSavedOccurrenceSourceContext(input: unknown): SavedOccurrenceSourceContext {
  const record = asRecord(input, 'saved occurrence source context');
  const timeRangeMs = validateRange(record.timeRangeMs, 'timeRangeMs', 'start', 'end');
  const charSpan = validateRange(record.charSpan, 'charSpan', 'start', 'end');
  const base: SavedOccurrenceSourceContext = {
    mediaId: requireString(record, 'mediaId'),
    mediaPath: requireString(record, 'mediaPath'),
    mediaFingerprint: requireSha256(record, 'mediaFingerprint'),
    subtitleTrackId: requireString(record, 'subtitleTrackId'),
    cueId: requireString(record, 'cueId'),
    timeRangeMs,
    tokenSpan: validateTokenSpan(record.tokenSpan),
    charSpan,
  };
  if (record.transcriptTrack === undefined) return base;
  return { ...base, transcriptTrack: validateTranscriptTrackSourceContext(record.transcriptTrack) };
}

function optionalString(record: Record<string, unknown>, key: string): string | undefined {
  const value = record[key];
  if (value === undefined) return undefined;
  if (typeof value !== 'string') throw new TypeError(`${key} must be a string`);
  return value;
}

function optionalBoolean(record: Record<string, unknown>, key: string): boolean | undefined {
  const value = record[key];
  if (value === undefined) return undefined;
  if (typeof value !== 'boolean') throw new TypeError(`${key} must be a boolean`);
  return value;
}

function validateWarningFlags(value: unknown): readonly TranscriptWarningFlag[] {
  if (!Array.isArray(value)) throw new TypeError('transcriptTrack.warningFlags must be an array');
  return value.map((flag) => {
    if (typeof flag !== 'string') throw new TypeError('transcriptTrack.warningFlags entries must be strings');
    return flag as TranscriptWarningFlag;
  });
}

export function validateTranscriptTrackSourceContext(input: unknown): TranscriptTrackSourceContext {
  const record = asRecord(input, 'transcript track source context');
  const result: TranscriptTrackSourceContext = {
    trackId: requireString(record, 'trackId'),
    status: requireString(record, 'status') as TranscriptTrackSourceContext['status'],
    sourceKind: requireString(record, 'sourceKind') as TranscriptTrackSourceContext['sourceKind'],
    trackVersion: requireNonNegativeInteger(record, 'trackVersion'),
    warningFlags: validateWarningFlags(record.warningFlags),
  };
  const optionalFields = [
    'sourceUrl',
    'sourceVideoId',
    'retrievedAt',
    'generatedAt',
    'engine',
    'modelName',
    'modelVersion',
    'parentTrackId',
    'approvedAt',
  ] as const;
  const mutable = result as Record<string, unknown>;
  for (const field of optionalFields) {
    const value = optionalString(record, field);
    if (value !== undefined) mutable[field] = value;
  }
  const parentTrackSha256 = record.parentTrackSha256 === undefined ? undefined : requireSha256(record, 'parentTrackSha256');
  if (parentTrackSha256 !== undefined) mutable.parentTrackSha256 = parentTrackSha256;
  const isAutoGenerated = optionalBoolean(record, 'isAutoGenerated');
  if (isAutoGenerated !== undefined) mutable.isAutoGenerated = isAutoGenerated;
  return result;
}
