import { describe, expect, it } from 'vitest';
import { LocalStore, SavedOccurrenceService, ExportService } from '../../packages/storage/src';
import {
  makeCue,
  makeMediaAsset,
  makeSubtitleTrack,
  validateSavedOccurrenceSourceContext,
} from '../../packages/domain/src';

function setupDraftTranscriptStore() {
  const store = new LocalStore();
  const service = new SavedOccurrenceService(store);
  const asset = makeMediaAsset({
    title: 'Authorized public-domain sample',
    originalPath: 'blob:authorized-sample',
    contentSha256: 'sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    durationMs: 2200,
    container: 'webm',
    sizeBytes: 1234,
    privacyLabel: 'owned',
  });
  store.putMediaAsset(asset);
  const track = makeSubtitleTrack({
    mediaId: asset.id,
    language: 'pl',
    role: 'target',
    format: 'json',
    sourceKind: 'owned',
    sourcePath: 'youtube:abcdefghijk:pl',
    contentSha256: 'sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    isActive: true,
    transcriptStatus: 'draft',
    transcriptSourceKind: 'youtube-auto-caption',
    provenance: {
      sourceUrl: 'https://www.youtube.com/watch?v=abcdefghijk',
      sourceVideoId: 'abcdefghijk',
      retrievedAt: '2026-06-22T12:00:00.000Z',
      language: 'pl',
      isAutoGenerated: true,
      warningFlags: ['autoCaption', 'timingUnverified'],
    },
    qualityReport: {
      segmentCount: 1,
      coverageDurationMs: 2200,
      emptyCueCount: 0,
      overlongCueCount: 0,
      overlappingCueCount: 0,
      suspiciousGapCount: 0,
      warningFlags: ['autoCaption', 'timingUnverified'],
      manualCorrectionCount: 0,
    },
  });
  store.putSubtitleTrack(track);
  const cue = makeCue({
    trackId: track.id,
    cueIndex: 1,
    startMs: 0,
    endMs: 2200,
    text: 'To jest niedokładny napis.',
    normalizedText: 'to jest niedokładny napis.',
    textSha256: 'sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
  });
  store.putCue(cue);
  const sourceContext = validateSavedOccurrenceSourceContext({
    mediaId: asset.id,
    mediaPath: asset.originalPath,
    mediaFingerprint: asset.contentSha256,
    subtitleTrackId: track.id,
    cueId: cue.id,
    timeRangeMs: { start: cue.startMs, end: cue.endMs },
    tokenSpan: { startToken: 0, endToken: 4 },
    charSpan: { start: 0, end: cue.text.length },
  });
  return { store, service, asset, track, cue, sourceContext };
}

describe('P7 transcript lifecycle domain gates', () => {
  it('defaults existing user subtitle files to approved track lifecycle metadata', () => {
    const track = makeSubtitleTrack({
      mediaId: 'media-1',
      language: 'pl',
      role: 'target',
      format: 'srt',
      sourceKind: 'owned',
      sourcePath: 'owned.pl.srt',
      contentSha256: 'sha256:dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
      isActive: true,
    });

    expect(track.transcriptStatus).toBe('approved');
    expect(track.transcriptSourceKind).toBe('user-subtitle-file');
    expect(track.provenance.language).toBe('pl');
    expect(track.provenance.warningFlags).toEqual([]);
  });

  it('refuses to save learner occurrences from draft YouTube or ASR transcript tracks', () => {
    const { service, asset, cue, sourceContext } = setupDraftTranscriptStore();

    expect(() => service.saveSelection({
      kind: 'sentence',
      language: 'pl',
      displayText: cue.text,
      mediaId: asset.id,
      cueId: cue.id,
      startMs: cue.startMs,
      endMs: cue.endMs,
      sourceContext,
    })).toThrow(/approved transcript/i);
  });

  it('exports approved transcript provenance and warning flags with learner source contexts', () => {
    const { store, service, asset, track, cue, sourceContext } = setupDraftTranscriptStore();
    store.putSubtitleTrack({ ...track, transcriptStatus: 'approved' });
    service.saveSelection({
      kind: 'sentence',
      language: 'pl',
      displayText: cue.text,
      mediaId: asset.id,
      cueId: cue.id,
      startMs: cue.startMs,
      endMs: cue.endMs,
      sourceContext,
    });

    const manifest = new ExportService(store, '0.0.0-p7').buildManifest();

    expect(manifest.content.sourceContexts).toHaveLength(1);
    expect(manifest.content.sourceContexts[0]!.transcriptTrack).toMatchObject({
      trackId: track.id,
      status: 'approved',
      sourceKind: 'youtube-auto-caption',
      sourceVideoId: 'abcdefghijk',
      warningFlags: ['autoCaption', 'timingUnverified'],
    });
  });
});
