import { describe, expect, it } from 'vitest';
import {
  approveTranscriptTrack,
  createAppModel,
  createCorrectedTranscriptVersion,
  generateElevenLabsScribeDraft,
  generateLocalAsrDraft,
  importFixtureMediaAndSubtitles,
  importYouTubeCaptionCandidate,
  makeFakeElevenLabsScribeProvider,
  makeFakeLocalAsrProvider,
  makeFakeYouTubeCaptionProvider,
  planYtDlpMediaAcquisition,
  saveSentenceFromCue,
} from '../../apps/web/src/model';

describe('P7 transcript provider adapters and correction lifecycle', () => {
  it('refuses ElevenLabs Scribe drafts before explicit provider consent and adapter execution', async () => {
    const model = createAppModel();
    await importFixtureMediaAndSubtitles(
      model,
      'fixtures/media/synthetic-polish-dialogue.webm',
      'fixtures/subtitles/synthetic-polish-dialogue.target.srt',
      'fixtures/subtitles/synthetic-polish-dialogue.native.srt',
    );
    const provider = makeFakeElevenLabsScribeProvider({
      language: 'pl',
      modelName: 'scribe_v2',
      modelVersion: 'test-fixture',
      segments: [{
        startMs: 0,
        endMs: 1500,
        text: 'Szkic ElevenLabs.',
      }],
    });

    await expect(generateElevenLabsScribeDraft(model, provider, {
      language: 'pl',
      allowOnlineProvider: false,
    })).rejects.toThrow(/ElevenLabs|provider consent|disabled/i);
    expect(provider.calls).toBe(0);
  });

  it('creates ElevenLabs Scribe draft tracks with first-class word timings and provider provenance', async () => {
    const model = createAppModel();
    await importFixtureMediaAndSubtitles(
      model,
      'fixtures/media/synthetic-polish-dialogue.webm',
      'fixtures/subtitles/synthetic-polish-dialogue.target.srt',
      'fixtures/subtitles/synthetic-polish-dialogue.native.srt',
    );
    const provider = makeFakeElevenLabsScribeProvider({
      language: 'pl',
      modelName: 'scribe_v2',
      modelVersion: 'test-fixture',
      segments: [{
        startMs: 0,
        endMs: 1500,
        text: 'Cześć świecie.',
        confidence: 0.93,
        words: [
          { wordIndex: 0, text: 'Cześć', charStart: 0, charEnd: 5, startMs: 0, endMs: 620, confidence: 0.96, speakerId: 'speaker_0' },
          { wordIndex: 1, text: 'świecie', charStart: 6, charEnd: 13, startMs: 700, endMs: 1400, confidence: 0.91, speakerId: 'speaker_0' },
        ],
      }],
    });

    const result = await generateElevenLabsScribeDraft(model, provider, {
      language: 'pl',
      allowOnlineProvider: true,
    });
    const timings = model.store.listTranscriptWordTimingsForTrack(result.track.id);

    expect(provider.calls).toBe(1);
    expect(result.track.transcriptStatus).toBe('draft');
    expect(result.track.transcriptSourceKind).toBe('online-asr');
    expect(result.track.provenance.engine).toBe('elevenlabs');
    expect(result.track.provenance.modelName).toBe('scribe_v2');
    expect(result.track.provenance.modelVersion).toBe('test-fixture');
    expect(result.track.provenance.warningFlags).toEqual(expect.arrayContaining(['asrDraft', 'qualityUnreviewed']));
    expect(timings).toHaveLength(2);
    expect(timings[0]).toMatchObject({
      cueId: result.cues[0]!.id,
      trackId: result.track.id,
      wordIndex: 0,
      text: 'Cześć',
      normalizedText: 'cześć',
      charStart: 0,
      charEnd: 5,
      startMs: 0,
      endMs: 620,
      confidence: 0.96,
      speakerId: 'speaker_0',
      sourceKind: 'provider-word-timing',
      engine: 'elevenlabs',
      modelName: 'scribe_v2',
      modelVersion: 'test-fixture',
    });
    expect(Object.values(model.store.snapshot().savedItems)).toHaveLength(0);
  });

  it('imports YouTube captions as draft candidates only after explicit public-read authorization', async () => {
    const model = createAppModel();
    const provider = makeFakeYouTubeCaptionProvider({
      videoId: 'abcdefghijk',
      language: 'pl',
      isAutoGenerated: true,
      segments: [{ startMs: 0, endMs: 1800, text: 'Provider caption draft.' }],
    });

    await expect(importYouTubeCaptionCandidate(model, {
      url: 'https://www.youtube.com/watch?v=abcdefghijk',
      language: 'pl',
      allowPublicRead: false,
    }, provider)).rejects.toThrow(/disabled|authorization/i);
    expect(provider.calls).toBe(0);

    const result = await importYouTubeCaptionCandidate(model, {
      url: 'https://www.youtube.com/watch?v=abcdefghijk',
      language: 'pl',
      allowPublicRead: true,
    }, provider);

    expect(provider.calls).toBe(1);
    expect(result.track.transcriptStatus).toBe('draft');
    expect(result.track.transcriptSourceKind).toBe('youtube-auto-caption');
    expect(result.track.provenance.sourceVideoId).toBe('abcdefghijk');
    expect(result.track.provenance.warningFlags).toContain('autoCaption');
    expect(model.cues[0]?.text).toBe('Provider caption draft.');
    expect(Object.values(model.store.snapshot().savedItems)).toHaveLength(0);
  });

  it('creates local ASR drafts behind a fakeable local adapter without mutating saved learner state', async () => {
    const model = createAppModel();
    await importFixtureMediaAndSubtitles(
      model,
      'fixtures/media/synthetic-polish-dialogue.webm',
      'fixtures/subtitles/synthetic-polish-dialogue.target.srt',
      'fixtures/subtitles/synthetic-polish-dialogue.native.srt',
    );
    const provider = makeFakeLocalAsrProvider({
      engine: 'fake-local-asr',
      modelName: 'tiny-test-model',
      language: 'pl',
      segments: [{ startMs: 0, endMs: 1500, text: 'Lokalny szkic ASR.' }],
    });

    const result = await generateLocalAsrDraft(model, provider);

    expect(provider.calls).toBe(1);
    expect(result.track.transcriptStatus).toBe('draft');
    expect(result.track.transcriptSourceKind).toBe('local-asr');
    expect(result.track.provenance.engine).toBe('fake-local-asr');
    expect(result.track.provenance.modelName).toBe('tiny-test-model');
    expect(result.track.provenance.warningFlags).toContain('asrDraft');
    expect(Object.values(model.store.snapshot().savedItems)).toHaveLength(0);
  });

  it('keeps raw drafts immutable, creates corrected versions, and allows study saves only after approval', async () => {
    const model = createAppModel();
    const provider = makeFakeYouTubeCaptionProvider({
      videoId: 'abcdefghijk',
      language: 'pl',
      isAutoGenerated: true,
      segments: [{ startMs: 0, endMs: 1800, text: 'Bad draft text.' }],
    });
    const imported = await importYouTubeCaptionCandidate(model, {
      url: 'https://www.youtube.com/watch?v=abcdefghijk',
      language: 'pl',
      allowPublicRead: true,
    }, provider);
    const draftCue = model.cues[0]!;

    await expect(saveSentenceFromCue(model, draftCue)).rejects.toThrow(/approved transcript/i);

    const corrected = await createCorrectedTranscriptVersion(model, imported.track.id, [{
      cueId: draftCue.id,
      text: 'Corrected transcript text.',
    }]);
    const rawCue = model.store.getCue(draftCue.id)!;

    expect(rawCue.text).toBe('Bad draft text.');
    expect(corrected.track.transcriptStatus).toBe('correcting');
    expect(corrected.track.provenance.parentTrackId).toBe(imported.track.id);
    expect(model.targetTrackId).toBe(corrected.track.id);
    expect(model.cues[0]?.text).toBe('Corrected transcript text.');

    approveTranscriptTrack(model, corrected.track.id, '2026-06-22T12:30:00.000Z');
    const saved = await saveSentenceFromCue(model, model.cues[0]!);

    expect(model.store.getSubtitleTrack(corrected.track.id)?.transcriptStatus).toBe('approved');
    expect(model.store.getSubtitleTrack(corrected.track.id)?.qualityReport?.approvedAt).toBe('2026-06-22T12:30:00.000Z');
    expect(saved?.displayText).toBe('Corrected transcript text.');
  });
});

describe('P7 safe yt-dlp command planning', () => {
  it('plans caption/media acquisition without cookies, credential paths, DRM bypass flags, or repo-relative output paths', () => {
    const plan = planYtDlpMediaAcquisition({
      url: 'https://www.youtube.com/watch?v=abcdefghijk',
      outputDirectory: '/tmp/lingotorte-authorized-media',
      includeMedia: true,
      allowMediaDownload: true,
    });

    expect(plan.argv).toEqual([
      'yt-dlp',
      '--no-playlist',
      '--write-subs',
      '--write-auto-subs',
      '--sub-format',
      'srt/vtt',
      '--paths',
      '/tmp/lingotorte-authorized-media',
      'https://www.youtube.com/watch?v=abcdefghijk',
    ]);
    expect(plan.argv.join(' ')).not.toMatch(/cookies|browser|username|password|decrypt|drm/i);
  });

  it('refuses media download without rights confirmation and refuses repo-relative output paths', () => {
    expect(() => planYtDlpMediaAcquisition({
      url: 'https://www.youtube.com/watch?v=abcdefghijk',
      outputDirectory: '/tmp/lingotorte-captions-only',
      includeMedia: true,
      allowMediaDownload: false,
    })).toThrow(/rights|permission/i);

    expect(() => planYtDlpMediaAcquisition({
      url: 'https://www.youtube.com/watch?v=abcdefghijk',
      outputDirectory: 'downloads',
      includeMedia: false,
      allowMediaDownload: false,
    })).toThrow(/absolute|repo/i);
  });
});
