import { describe, expect, it } from 'vitest';
import { createDisabledLookupAdapter, defaultProviderPolicy } from '../../packages/domain/src/providerPolicy';
import {
  createAppModel,
  importYouTubeCaptionCandidate,
  makeFakeYouTubeCaptionProvider,
} from '../../apps/web/src/model';
import { withNoNetwork } from './networkTrap';

describe('provider-disabled no-network harness', () => {
  it('returns a typed disabled lookup result without attempting network access', async () => {
    const adapter = createDisabledLookupAdapter(defaultProviderPolicy());

    const result = await withNoNetwork(async () =>
      adapter.lookupToken({
        token: 'Cześć',
        language: 'pl',
        cueId: 'cue.pl.0001',
      }),
    );

    expect(result.networkAttempts).toEqual([]);
    expect(result.value).toEqual({
      status: 'disabled',
      adapterId: 'lingotorte.disabled-lookup',
      privacyMode: 'local',
      reason: 'online-providers-disabled',
    });
  });

  it('blocks transcript caption import before adapter execution when explicit authorization is absent', async () => {
    const model = createAppModel();
    const provider = makeFakeYouTubeCaptionProvider({
      videoId: 'abcdefghijk',
      language: 'pl',
      isAutoGenerated: false,
      segments: [{ startMs: 0, endMs: 1000, text: 'Should not be imported.' }],
    });

    const result = await withNoNetwork(async () => {
      await expect(importYouTubeCaptionCandidate(model, {
        url: 'https://www.youtube.com/watch?v=abcdefghijk',
        language: 'pl',
        allowPublicRead: false,
      }, provider)).rejects.toThrow(/authorization/i);
      return provider.calls;
    });

    expect(result.networkAttempts).toEqual([]);
    expect(result.value).toBe(0);
    expect(model.cues).toHaveLength(0);
  });

  it('fails the test harness on attempted fetch while providers are disabled', async () => {
    await expect(
      withNoNetwork(() => fetch('https://example.invalid/provider')),
    ).rejects.toThrow(/Network disabled during provider-off test/);
  });
});
